name: Pull Request Control for Staging Branch

permissions:
  pull-requests: write
  issues: write

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check target branch
        id: check-branch
        run: |
          # Get the target branch of the pull request
          TARGET_BRANCH="${{ github.event.pull_request.base.ref }}"
          
          # Check if the target branch is "staging"
          if [ "$TARGET_BRANCH" = "staging" ]; then
            echo "The target branch is staging, checking the pull request author."
            echo "is_staging=true" >> $GITHUB_OUTPUT
          else
            echo "The target branch is not staging, skipping the check."
            echo "is_staging=false" >> $GITHUB_OUTPUT
          fi

      - name: Check PR author for staging branch
        id: check-author
        if: steps.check-branch.outputs.is_staging == 'true'
        continue-on-error: true
        run: |
          # List of users allowed to create pull requests to the staging branch
          ALLOWED_USERS="phtrung212"

          # Get the pull request author's username
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"

          # Check if the author is in the allowed users list
          if [[ "$ALLOWED_USERS" != *"$PR_AUTHOR"* ]]; then
            echo "User $PR_AUTHOR is not authorized to create pull requests to the staging branch."
            exit 1
          else
            echo "User $PR_AUTHOR is authorized to create pull requests to the staging branch."
          fi

      - name: Close PR if unauthorized for staging branch
        if: steps.check-branch.outputs.is_staging == 'true' && steps.check-author.outcome == 'failure'
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          COMMENT_BODY="Closed: User @${PR_AUTHOR} is not authorized to create pull requests to the staging branch."

          echo "Adding comment to pull request #${PR_NUMBER}"
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments \
            -d "{\"body\": \"${COMMENT_BODY}\"}"

          echo "Closing pull request #${PR_NUMBER}"
          curl -X PATCH \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER} \
            -d '{"state": "closed"}'
